name: market-analysis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - jupyter
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - pip
  - pyarrow
  - fastparquet
  - tqdm
  - pip:
    - yfinance